const ADD_NEW_NOTE = "ADD_NEW_NOTE";
const ADD_CHORD_NOTE = "ADD_CHORD_NOTE";
const REMOVE_NOTE = "REMOVE_NOTE";
const REMOVE_CHORD_NOTE = "REMOVE_CHORD_NOTE";
const TOGGLE_TOOL = "TOGGLE_TOOL";
const UPDATE_NOTE = "UPDATE_NOTE";

module.exports = { 
    ADD_NEW_NOTE,
    ADD_CHORD_NOTE,
    REMOVE_NOTE,
    REMOVE_CHORD_NOTE,
    TOGGLE_TOOL,
    UPDATE_NOTE
}